# Generated by Django 2.2.8 on 2019-12-15 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片路径')),
                ('img_url', models.URLField(blank=True, null=True, verbose_name='图片跳转url')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片标题')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片描述')),
            ],
            options={
                'verbose_name': '展示轮播',
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='ChatMsgModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='微信openid')),
                ('chat_type', models.CharField(choices=[('img', '图片'), ('msg', '信息')], default='msg', max_length=50)),
                ('content', models.CharField(blank=True, max_length=500, null=True, verbose_name='咨询内容')),
            ],
            options={
                'verbose_name': '聊天留言信息',
                'db_table': 'chat_msg',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品标题')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价')),
                ('product_type', models.CharField(choices=[('product', '产品'), ('production', '作品')], default='product', max_length=50)),
                ('check_num', models.IntegerField(blank=True, null=True, verbose_name='查看次数')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('specification', models.CharField(blank=True, max_length=1000, null=True, verbose_name='规格参数')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品描述')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '展示产品',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_type', models.CharField(choices=[('default', '主图'), ('slave', '从图')], default='slave', max_length=50)),
                ('img_path', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片路径')),
                ('img_url', models.URLField(blank=True, null=True, verbose_name='图片跳转url')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ProductModel', verbose_name='关联外键')),
            ],
            options={
                'verbose_name': '产品对应的图片',
                'db_table': 'images',
            },
        ),
    ]
