# Generated by Django 2.2.8 on 2019-12-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='图标路径')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='父类id')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='路径')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类名称')),
                ('style', models.CharField(blank=True, max_length=50, null=True, verbose_name='样式')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分类表',
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.CategoryModel', verbose_name='外键'),
        ),
    ]
